### ISSUE TITLE
Updated the release-team's shadow application survey to add an opt-in option

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes-sigs/release-team-shadow-stats#10]
We would like to give the shadow applicant the option to opt-in to be included in the release team shadow application report. 

- [ ] Added an opt-in option to the release team shadow application template.

ref tracking issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

**Comment by leonardpahlke** [comment]
@jeremyrickard I think you shared the excel file for the 1.24 applicants, right. Do you have the power to update the template as well?

**Comment by jrsapi** [comment]
@leonardpahlke Rey Lejano is editing the current form for 1.25 shadow applications and you can coordinate with him.

**Comment by leonardpahlke** [comment]
Okay! Great thanks @reylejano :slightly_smiling_face:!

/assign @reylejano

**Comment by reylejano** [comment]
A opt-in option has been added to the v1.25 shadow application and reviewed by @JamesLaverack v1.24 lead, @jrsapi v1.24 EA, @jeremyrickard SIG Release TL, @jberkus SIG ContribEx, @cici37 v1.25 lead  and sent to SIG Release leads and TLs
/close
