### ISSUE TITLE
Define release-team-shadow report

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes-sigs/release-team-shadow-stats#8]
Currently, the diagrams (see [charts in the example folder](https://github.com/kubernetes-sigs/release-team-shadow-stats/tree/main/examples/plots)) are not structured. To share this information, a simple report template should be defined. This report should be publicly available and must be coordinated with ContribEx.

depending issue: [consult contribex which charts can be shared publicly in a report](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/7).

ref tracking issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

**Comment by leonardpahlke** [comment]
/assign

Structure of the report:

_Title of the report_: Kubernetes Release Team Shadow Application Report for the release cycle 1.XX
1. Introduction
   1. _Purpose of the report_ (tbd)
   2. Structure of the report & Table fo contents
2. General charts
   1. chart 1
   2. chart ...
3. Charts by team
   1. Team 1
       1. chart 1
       2. chart ...
   2. Team ... 

what do you think @jberkus @cici37 @reylejano

After discussing the structure, I would document it in the repo to create the report manually for now, but we can automate it later, see issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/14

**Comment by jberkus** [comment]
Seems fine?  We'll make changes with 1.26, just because then we'll have something for comparison.
