### ISSUE TITLE
Document process: create, review and share the release-team-shadow-stats report

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes-sigs/release-team-shadow-stats#9]
To share the current status of the release team's shadow application program with the community, the report must be created, reviewed, and then shared with the community. These three phases must be defined and documented.

Define and document the phases.
- [ ] Phase 1.) **How to create the report**: see https://github.com/kubernetes/sig-release/issues/1883 for [k/sig-release](https://github.com/kubernetes/sig-release) and this output on https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/6.
- [ ] Phase 2.) **Review of the report**: how should the report be reviewed (github issue to track review progress?) (involved parties...) 
- [ ] Phase 3.) **Share the report with the community**: how should the report be shared (google groups?) who cares (the release manager?)

Central documentation on how to use the tool should be included in the README file, but more specific information can be referenced elsewhere (e.g., in the k/sig-release file)

ref tracking issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

**Comment by leonardpahlke** [comment]
it makes sense to work first on the improve usability issue before starting documenting the process 
https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/6

**Comment by ggold7046** [comment]
Hi, what is the procedure to join the `release-team-shadow` group ?

**Comment by leonardpahlke** [comment]
Hi, please checkout the kubernetes/sig-release repo for info https://github.com/kubernetes/sig-release/blob/master/release-team/shadows.md -- if you may have any further questions, please ask in #sig-release K8s slack channel :)
